### ISSUE TITLE
Remove categories on top?

### ISSUE THREAD

**Issue by TheNomad11** [b2evolution/bricks_skin#1]
Great skin! I have one issue though: How can I remove the list of categories on the top of the front page? I've gone through all possible settings but haven't found out how. Thanks!

**Comment by Ariflaw** [comment]
Hi, I've update for the list of categories option. Now you can enable or disable that feature with the skin options.

Thanks

![screenshot](https://cloud.githubusercontent.com/assets/7199479/24947104/a1c9bc18-1f8f-11e7-9dcb-a26e384d4edc.png)

**Comment by TheNomad11** [comment]
Wow, perfect, thanks a lot!
